# Site settings
title: SacJS
email: derek@jsconf.us
description: >
  The Sacramento Javascript Meetup Group
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://sacjs.github.io
twitter_username: sac_js
github_username:  sacjs
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
